repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.650
    hooks:
    -   id: mypy

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: flake8
        args: ["--ignore","E501"]

