version: 2.1

orbs:
  lumigo-orb: &lumigo_orb_version lumigo/lumigo-orb@volatile

workflows:
  test-deploy:
    jobs:
    - lumigo-orb/print_orb_versions:
        lumigo_orb_version: *lumigo_orb_version

    - lumigo-orb/test:
        context: common

    - lumigo-orb/is_environment_available:
        context: common
        filters:
          branches:
            ignore: master

    - lumigo-orb/be-deploy:
        context: common
        requires:
          - lumigo-orb/is_environment_available

    - lumigo-orb/integration-test-prep:
        context: common
        run_test_cleanup: false
        requires:
          - lumigo-orb/be-deploy

    - lumigo-orb/integration-test-cleanup:
        name: pre-test-cleanup
        context: common
        requires:
          - lumigo-orb/integration-test-prep

    - lumigo-orb/integration-test-limited-flows:
        context: common
        run_test_cleanup: false
        requires:
          - pre-test-cleanup

    - lumigo-orb/integration-test-parallel:
        context: common
        run_test_cleanup: false
        requires:
          - lumigo-orb/integration-test-limited-flows

    - lumigo-orb/integration-test-cleanup:
        name: post-test-cleanup
        context: common
        requires:
          - lumigo-orb/integration-test-parallel

    - lumigo-orb/e2e-test:
        context: common
        requires:
          - lumigo-orb/integration-test-limited-flows

    - lumigo-orb/workflow-completed-successfully:
        context: common
        requires:
          - lumigo-orb/test
          - lumigo-orb/integration-test-parallel
          - lumigo-orb/e2e-test

    - lumigo-orb/deploy:
        context:
          - common
          - fury
          - twine
        filters:
          branches:
            only: master
        requires:
          - lumigo-orb/test
