version: 2.1
defaults: &defaults
  working_directory: ~/python-common-utils
  docker:
  - image: lumigo/ci:latest
    auth:
      username: lumigo
      password: $DOCKERHUB_PASSWORD
    # Specifically for our tests to run specifically.
    environment:
      USER: CI_USER
      AWS_ACCESS_KEY_ID: MOCK
      AWS_SECRET_ACCESS_KEY: MOCK

orbs:
  lumigo-orb: lumigo/lumigo-orb@volatile

commands:
  checkout_code:
    description: "Checkout code and test it"
    steps:
      - checkout
      - run:
            # Avoid annoying double runs after deploy.
            # See https://discuss.circleci.com/t/job-runs-even-when-tags-ignore-filter-is-triggered-when-combined-with-branches-only/20664
            name: Check if tagged
            command: |
              tags=$(git tag -l --points-at HEAD)
              echo "Tags $tags"
              if [[ ! -z "$tags" ]]
              then
                echo "A tagged commit, skip..."
                circleci step halt
              fi
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # https://discuss.circleci.com/t/activate-python-virtualenv-for-whole-job/14434
      - run: echo "source venv/bin/activate" >> $BASH_ENV
      - run: pip install pytest-cov
      - run: pre-commit install

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

workflows:
  test-deploy:
    jobs:
    - test:
        filters:
          branches:
            ignore: master
    - deploy:
        filters:
          branches:
            only: master

jobs:
  test:
    <<: *defaults
    steps:
      - lumigo-orb/checkout_utils
      - checkout_code
      - run: export AWS_DEFAULT_REGION=us-west-2 && export USER=CICD && ./scripts/checks.sh
      - run: ../utils/common_bash/defaults/code_cov.sh


  deploy:
    <<: *defaults
    steps:
      - lumigo-orb/checkout_utils
      - checkout_code
      - run: export AWS_DEFAULT_REGION=us-west-2 && export USER=CICD && ./scripts/checks.sh
      - run: ../utils/common_bash/defaults/code_cov.sh
      - run: ./scripts/bd_to_prod.sh
