version: 2.1

orbs:
  lumigo-orb: lumigo/lumigo-orb@volatile

workflows:
  test-deploy:
    jobs:
    - lumigo-orb/test
    - lumigo-orb/deploy:
        filters:
          branches:
            only: master
